apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-backend
  labels:              
    name: backend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      name: backend
  template:
    metadata:
      labels:
        name: backend
    spec:
      containers:
      - name: backend
        image: satyam19arya/social_media_backend:build-76
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
