apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-frontend
  labels:  
    name: frontend            
spec:
  replicas: 2 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      name: frontend
  template:
    metadata:
      labels:
        name: frontend
    spec:
      containers:
      - name: frontend
        image: satyam19arya/social_media_frontend:build-48
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
