apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp_backend
  labels:              
    name: backend
spec:
  replicas: 2 
  selector:
    matchLabels:
      name: backend
  template:
    metadata:
      labels:
        name: backend
    spec:
      containers:
      - name: backend
        image: satyam19arya/social_media_backend:build-3
        ports:
        - containerPort: 4000