apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-frontend
  labels:  
    name: frontend            
spec:
  replicas: 2 
  selector:
    matchLabels:
      name: frontend
  template:
    metadata:
      labels:
        name: frontend
    spec:
      containers:
      - name: frontend
        image: satyam19arya/social_media_frontend:build-22
        ports:
        - containerPort: 3000
